using System.Collections;
using System.Collections.Generic;
using System.Linq;
using Unity.VisualScripting;
using UnityEngine;
using UnityEngine.Serialization;

public class HardReset : MonoBehaviour
{

    // public GameObject StatLoewe;
    // public GameObject StatSchnecke;
    // public GameObject StatJuengling;
    //
    // public Transform StatTransLoewe;
    // public Transform StatTransSchnecke;
    // public Transform StatTransJuengling;

    public GameObject Cam;
    public Transform CamTrans;

    public GameObject[] Flowers;
    public Transform[] FlowerTrans;

    public GameObject[] Assets;
    public Transform[] AssetsTrans;
    public ReflectionProbe Probe;
    [SerializeField] TexturePainter TexPaint;



    

    void OnTriggerEnter(Collider col)
    {
        var statue = col.GetComponent<Statue>();
        if (statue != null)
        {
            ResetStatue(statue.StatueValues);
        }

    }

    private void ResetStatue(StatueValues statue)
    {
        // StatLoewe.transform.position = StatTransLoewe.position;
        // StatSchnecke.transform.position = StatTransSchnecke.position;
        // StatJuengling.transform.position = StatTransJuengling.position;
        //
        // StatLoewe.transform.eulerAngles = StatTransLoewe.eulerAngles;
        // StatSchnecke.transform.eulerAngles = StatTransSchnecke.eulerAngles;
        // StatJuengling.transform.eulerAngles = StatTransJuengling.eulerAngles;

        if(StatueSpawnController.Singleton.RequestStatueReset(statue))
        {
            // RenderSettings.skybox = TexPaint.SkyBoxHub;
            DynamicGI.UpdateEnvironment();
            Probe.RenderProbe();
            Reset(Cam, CamTrans);
            TexPaint.ResetAll();
            Resources.UnloadUnusedAssets();
        }
        
        ResetFlowers();
        ResetAssets();
        DeleteShields();
    }


    public void DeleteShields()
    {
        GameObject[] NewShield = GameObject.FindGameObjectsWithTag("Interactable");
        for (int i = 0; i < NewShield.Length; i++)
        {
            if(NewShield[i].name == "NewProtestShield")
            {
                Destroy(NewShield[i]);
            }
            
        }
    }

    private void Reset(GameObject obj, Transform trans)
    {
        obj.transform.position = trans.position;
        obj.transform.eulerAngles = trans.eulerAngles;
    }

    private void ResetFlowers()
    {
        for (int i = 0; i < Flowers.Count(); i++)
        {
            Flowers[i].transform.position = FlowerTrans[i].position;
            Flowers[i].transform.eulerAngles = FlowerTrans[i].eulerAngles;
        }
    }

    private void ResetAssets()
    {
        for (int i = 0; i < Assets.Count(); i++)
        {
            Assets[i].transform.position = AssetsTrans[i].position;
            Assets[i].transform.eulerAngles = AssetsTrans[i].eulerAngles;
        }
    }

    public void ResetAddOns()
    {
        ResetAssets();
        ResetFlowers();
    }

}
